### ISSUE TITLE
How to add package to spacemacs

### ISSUE THREAD

**Issue by veverjak** [dougm/go-projectile#12]
Hi, I am total emacs newbie, I've started with spacemacs and have no clue how to enable this package in it. 

Would anyone help?

**Comment by veverjak** [comment]
found it, solution was to add these to `~/.spacemacs` file:
```
   dotspacemacs-additional-packages
   '(
     go-projectile
     )
.
.
.
(defun dotspacemacs/user-config ()
  (require 'go-projectile)
  )
```

**Comment by Andre0991** [comment]
Just one thing: you probably can omit the `require`.

**Comment by veverjak** [comment]
it didn't work for me without `require` unfortunately.

**Comment by Andre0991** [comment]
Right. It depends on the package I guess.
