### ISSUE TITLE
Forked version of gocode should be used in tools list

### ISSUE THREAD

**Issue by kat-co** [dougm/go-projectile#18]
nsf/gocode is not being maintained, and a [fork](github.com/mdempsky/gocode) of the project has been made. The list of tools should be updated to reflect this (i.e. update [this line](https://github.com/dougm/go-projectile/blob/master/go-projectile.el#L66) to `github.com/mdempsky/gocode`).

**Comment by dougm** [comment]
Thanks, didn't know about the fork, are there details somewhere on how the fork differs?  nsf/gocode has recent updates, so it still seems to be maintained, though maybe only bug fixes?

**Comment by kat-co** [comment]
Please see https://github.com/nsf/gocode/commit/9f3c24f3a0fe7119e933616ddcc867356d271398. nsf/gocode has issues which prevent it from working after Go 1.11 (or maybe earlier, but that's when it broke for me).
