### ISSUE TITLE
Oracle no longer defines `go-oracle-mode`

### ISSUE THREAD

**Issue by bdarnell** [dougm/go-projectile#3]
`oracle.el` used to define its own minor mode, but now it just modifies `go-mode-map` when it is loaded. This causes errors in the `go-projectile` `go-mode-hook`.

https://github.com/golang/tools/commit/68b5f7541d840b07800dc21d83ebdaa8ca8a771f

**Comment by dougm** [comment]
@bdarnell thanks for the report and sorry for the delay, this is fixed in 43ba927
