### ISSUE TITLE
`rename.el` is now `go-rename.el`

### ISSUE THREAD

**Issue by bdarnell** [dougm/go-projectile#6]
https://github.com/golang/tools/commit/f941d540e399747b10540b096ff9300cb3a35ad9

The `autoload` in `go-projectile-tools-add-path` needs to be updated. Or maybe now that `go-rename` is [on melpa](http://melpa.org/#/go-rename) you could add that package as a dependency instead of setting up `load-path` and `autoload` yourself.

**Comment by dougm** [comment]
Thanks for the report and suggestions, should be fixed now.
